#Exp-5 

1.
SELECT 
ORDERS.OID, ORDERS.CID, ORDERS.SID, ORDERS.ODATE, ORDERS.O_AMT,
SALESMEN.SNAME
FROM ORDERS INNER JOIN SALESMEN
ON ORDERS.SID = SALESMEN.SID
WHERE EXTRACT(DAY FROM ORDERS.ODATE) < 10;

OP:
 oid  | cid  | sid  |   odate    |   o_amt   |    sname
------+------+------+------------+-----------+--------------
 O501 | C302 | S102 | 2009-01-02 | 500000.00 | CHINTAN SHAH
(1 row)

2.
SELECT SALESMEN.SNAME, MIN(ORDERS.O_AMT) AS MIN_AMT
FROM ORDERS INNER JOIN SALESMEN
ON ORDERS.SID = SALESMEN.SID
GROUP BY SALESMEN.SNAME;

OP:
    sname     | min_amt
--------------+------------
 AJAY PATEL   |   90000.05
 JIMIT DAVE   |    7500.75
 JAY PANDEY   |   15000.00
 VINAY MEHRA  |  250000.00
 CHINTAN SHAH |   27800.00
(5 rows)

3.
SELECT SALESMEN.SNAME, SUM(ORDERS.O_AMT) AS TOTAL_AMT
FROM ORDERS INNER JOIN SALESMEN
ON ORDERS.SID = SALESMEN.SID
GROUP BY SALESMEN.SNAME;

OP:
    sname     | total_amt
--------------+-----------
 AJAY PATEL   | 990000.05
 JIMIT DAVE   |  17500.75
 JAY PANDEY   | 415000.00
 VINAY MEHRA  | 250000.00
 CHINTAN SHAH | 832800.00
(5 rows)

4.

SELECT CUSTOMERS.CITY FROM 
ORDERS INNER JOIN CUSTOMERS 
ON ORDERS.CID = CUSTOMERS.CID
WHERE ORDERS.O_AMT IN
(SELECT MIN(O_AMT) FROM ORDERS);

OP:
  city
--------
 BARODA
(1 row)

