#Exp-1

1.
CREATE TABLE SALESMEN(
    SID VARCHAR(5),
    SNAME VARCHAR(20) NOT NULL,
    CITY VARCHAR(15) NOT NULL,
    SALARY NUMERIC(5,2),
    PRODUCT VARCHAR(20),
    TGTTOGET NUMERIC(5,2),
    COMM NUMERIC(6,2),
    PRIMARY KEY(SID)
);
=> SELECT * FROM SALESMEN;

2.
CREATE TABLE CUSTOMERS(
    CID VARCHAR(5) PRIMARY KEY,
    CNAME VARCHAR(20) NOT NULL,
    CITY VARCHAR(15) NOT NULL,
    STATE VARCHAR(15),
    PINCODE NUMERIC(8),
    PRODUCT VARCHAR(20),
    CLASS VARCHAR(1) DEFAULT 'A'
);
=> SQL DEFAULT Constraint : https://www.w3schools.com/sql/sql_default.asp 
=> SELECT * FROM CUSTOMERS;

3.
CREATE TABLE ORDERS(
    OID VARCHAR(5),
    CID VARCHAR(5),
    SID VARCHAR(5),
    PRODUCT VARCHAR(20),
    QTY NUMERIC(5),
    ODATE DATE NOT NULL,
    O_AMT NUMERIC(8,2) CHECK(O_AMT >= 0),
    PRIMARY KEY(OID),
    FOREIGN KEY(CID) REFERENCES CUSTOMERS(CID),
    FOREIGN KEY (SID) REFERENCES SALESMEN(SID)
);
=> SELECT * FROM ORDERS;


